name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fix
      run: sudo apt install libpcap -y
    - name: configure
      run: bash gentables.sh && ./configure
    - name: make
      run: make
    - name: ls *
      run: ls *
    - name: tree
      run: tree
